# Generated by Django 3.2.6 on 2021-10-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thumb',
            new_name='thumbnail',
        ),
    ]
