# Generated by Django 3.2.6 on 2021-10-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_thumb_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Author', max_length=60),
        ),
    ]
