# Generated by Django 3.2.6 on 2021-10-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('new', 'NEW'), ('good', 'GOOD'), ('used', 'USED')], default='new', max_length=10),
        ),
    ]
