# Generated by Django 3.2.6 on 2021-10-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
