# Generated by Django 3.2.6 on 2021-10-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
    ]
