# Generated by Django 3.2.6 on 2021-11-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('rent', 'RENT'), ('sale', 'SALE')], default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
