# Generated by Django 3.2.6 on 2021-11-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20211101_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('romance', 'Romance')], default=('romance', 'Romance'), max_length=10),
        ),
    ]
