# Generated by Django 3.2.6 on 2021-11-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('romance', 'Romance'), ("children's book", "Children's Book")], default='romance', max_length=60),
        ),
    ]
