# Generated by Django 3.2.6 on 2021-11-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_bookgenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
