# Generated by Django 3.2.6 on 2021-11-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_remove_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
