# Generated by Django 3.2.9 on 2021-12-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_rename_bookrented_bookrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrent',
            name='books',
        ),
        migrations.AddField(
            model_name='bookrent',
            name='books',
            field=models.ForeignKey(default=None, help_text='books user have rented', on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
