# Generated by Django 3.2.9 on 2022-02-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20211213_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='synopsis',
        ),
    ]
