# Generated by Django 3.2.9 on 2022-02-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_auto_20220209_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
