# Generated by Django 3.2.9 on 2022-02-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookavailability',
            name='daterange',
            field=models.CharField(default='30', max_length=10),
        ),
    ]
