# Generated by Django 3.2.9 on 2022-02-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_book_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookGenre',
        ),
    ]
