# Generated by Django 3.2.9 on 2022-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_delete_bookgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookavailability',
            name='price',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
