# Generated by Django 3.2.9 on 2022-03-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_bookqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
