# Generated by Django 3.2.9 on 2022-03-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_book_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=b'I01\n', max_length=200),
        ),
        migrations.DeleteModel(
            name='BookQr',
        ),
    ]
