# Generated by Django 4.0.3 on 2022-03-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_auto_20220304_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('picture', models.ImageField(blank=True, default=None, upload_to='')),
                ('priority', models.CharField(blank=True, max_length=10)),
                ('active', models.CharField(blank=True, default='false', max_length=10)),
            ],
        ),
    ]
