# Generated by Django 4.0.3 on 2022-03-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0042_banner_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='description',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='banner',
            name='caption_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
