# Generated by Django 3.2.9 on 2022-02-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='deleted',
            field=models.CharField(default='false', max_length=255),
        ),
    ]
