# Generated by Django 3.2.9 on 2022-02-03 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_publicchatroom_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='user_delete', to=settings.AUTH_USER_MODEL),
        ),
    ]
