# Generated by Django 3.2.9 on 2022-02-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_publicchatroom_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicchatroom',
            name='deleted',
        ),
    ]
