# Generated by Django 3.2.9 on 2022-02-24 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_relatedimage'),
        ('chat', '0004_remove_publicchatroom_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
