# Generated by Django 3.2.6 on 2021-11-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
    ]
